version: "3.9"
services:
  api:
    image: kalambagames/job-assignment-backend
    command: [ "/app/wait-for", "db:3306", "--", "npm", "run", "start" ]
    restart: always
    environment:
      DATABASE_URL: mysql://root:password@db:3306/assignment
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    image: mysql:8.0.25
    platform: linux/amd64
    cap_add:
      - SYS_NICE # fixes "mbind: Operation not permitted"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: assignment
    ports:
      - 3307:3306
